[tool.poetry]
name = "docker-tskit"
version = "0.1.0"
description = "Docker image with tskit software"
authors = ["Paolo Cozzi <bunop@libero.it>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
tskit = "^0.5.6"
tsinfer = "^0.3.1"
tsdate = "^0.1.7"
click = "^8.1.7"
cyvcf2 = "^0.30.28"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
