[tool.poetry]
name = "docker-tskit"
version = "0.5.20"
description = "Docker image with tskitetude software"
authors = ["Paolo Cozzi <bunop@libero.it>"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
tskitetude = { git = "https://github.com/bunop/TSKITetude.git", rev = "45638ba214d2579454dd1d061d8c0ce9092a2e7a" }


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
